name: votting_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^9.1.1
  flutter_native_splash: ^2.3.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # You might want to remove or comment out one of these flutter_lints entries:
  # flutter_lints: ^3.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo-development.jpg
  # branding: assets/branding-development.png
  color_dark: "#121212"
  image_dark: assets/logo-development.jpg
  # branding_dark: assets/branding-development.png
  android_12:
    image: assets/logo-development.jpg
    icon_background_color: "#ffffff"
    image_dark: assets/logo-development.jpg
    icon_background_color_dark: "#121212"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/

